### ISSUE TITLE
Making Rounded Corners for the Bars instead of keeping them square.

### ISSUE THREAD

**Issue by Alaska18** [krharsh17/barview-android#34]

**Comment by Meghdut-Mandal** [comment]
I want to work on this issue

**Comment by krharsh17** [comment]
@Alaska18 Next time when you're opening an issue, make sure that you clearly specify in the description whether you want to work on that issue or not. Since you've already raised a PR for it, I'm going to assign it to you this time. But from the next time, if you do not get an issue assigned to yourself before raising a PR, your PR will be ignored and the issue will be assigned to the first person who claims it.

**Comment by vinay2214** [comment]
I would like to work on it

**Comment by 8426988382** [comment]
I would like to work on this issue.

**Comment by Akansha2202** [comment]
i would like to work on this issue.
